version: "3.9"

networks:
  gitea:
    external: false

services:
  server:
    image: docker.gitea.com/gitea:1.23.7
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      # if you want to use the mysql image, you can uncomment the following code and comment the postgres code above
      # - GITEA__database__DB_TYPE=mysql
      # - GITEA__database__HOST=db:3306
      # - GITEA__database__NAME=gitea
      # - GITEA__database__USER=gitea
      # - GITEA__database__PASSWD=gitea
    restart: always
    networks:
      - gitea
    volumes:
      - ~/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: gitea-db-postgres
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea
    ports:
      - "5432:5432"
    volumes:
      - ~/postgres:/var/lib/postgresql/data
    ## if you want to use the mysql image, you can uncomment the following code and comment the postgres code above
  # db:
  #   image: mysql:8.0
  #   restart: always
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=gitea
  #     - MYSQL_DATABASE=gitea
  #     - MYSQL_USER=gitea
  #     - MYSQL_PASSWORD=gitea
  #   networks:
  #     - gitea
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ~/mysql:/var/lib/mysql
